---
ansible_user: "ansible"
ansible_python_interpreter: "/usr/local/bin/python"
ansible_authorized_keys_file: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLklW3+HXkG0N6M1SG76WSuA4uNbkiVo3bojCox2ogv ansible-generated on ansible2.servers.bornhack.org

poudriere_package_set: 'freebsd_12_2_amd64-default'

users:
  tykling:
    comment: "Thomas Steen Rasmussen"
    key: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOZq1LdOdPDYnoQWn+87JafplL6IhDGvgytBfhItydgq user@bornhack
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPHWipJzu9PuTrVxRAk+0GNH1HqAomhPyrwrB4MQN7U7 user@bornhack-ssh
    sudo: True
  valberg:
    comment: "Víðir Valberg Guðmundsson"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUmGeHc6QXDcJHkmVxbTUv04Q3vs20avquoGr6eOkkvYbcgjuFnBOOtvs2Nul1odcvvnHa1nN7DfL8XJamiwsB1B/xe2seaNS1axgwk9XowlVN9pgga8gsC+4gZWBtSObG2GR8n4NtPENzPmW5deNn8dRpTvULPMxZ0VRE9yNQOx8v8w85yYh+vxbbkWGVDYJU23yuJI50U9y6bXxNHinsACDFBeR/giXDlw29TaOaSxz0R6zrRPBoX+V68RyWwBL+KWQKtX2ULtJI40S98Ohd6p41bIxYHCBS/zroqNne8PjYOLcHHsjHUGfTvhcS5a3zdz/iHsvsaOOjFjsydAXH valberg"
    sudo: True
  fj:
    comment: "Flemming Jacobsen"
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINWdikBZUtNb8JMgT6tkuG+B1+ZAGmrq5PySWrNr1bFF fj@home"
    sudo: True

certgrinder_ssh_server: "certgrinder1.servers.bornhack.org"
certgrinder_ssh_server_pubkey: "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBn2WYu5g8Q/G280wsjiPUEthAraSDmaOO6NKUH+ClTMXsuf31ZVTikvrQ5S9AUvkic+2eTaABz7VVFRTVXFWg8="
certgrinder_redirect_url: "http://certgrinder.bornhack.org"
certgrinder_admin_email: "sysadm@bornhack.org"

etcaliases_root_forward_email: "sysadm@bornhack.org"
ansible_admin_email: "sysadm@bornhack.org"
nullmailer_smarthost: "mail.bornhack.org"

dns_resolver_ips:
  - "91.239.100.100"
  - "89.233.43.71"
  - "2001:67c:28a4::"
  - "2a01:3a0:53:53::"
