---
- name: Install postfix
  become: yes
  pkgng:
    name=postfix
    state=present

- name: Enable postfix
  become: yes
  service:
    name=postfix
    enabled=yes

- name: Copy postfix main.cf
  become: yes
  template:
    src=main.cf.j2
    dest=/usr/local/etc/postfix/main.cf

- name: Copy postfix smtpd_sender_login_maps.sql
  become: yes
  template:
    src=smtpd_sender_login_maps.sql
    dest=/usr/local/etc/postfix/smtpd_sender_login_maps.sql
    mode=0600

- name: Copy postfix virtual_alias_maps.sql
  become: yes
  template:
    src=virtual_alias_maps.sql
    dest=/usr/local/etc/postfix/virtual_alias_maps.sql
    mode=0600

- name: Copy postfix virtual_mailbox_maps.sql
  become: yes
  template:
    src=smtpd_sender_login_maps.sql
    dest=/usr/local/etc/postfix/virtual_mailbox_maps.sql
    mode=0600

- name: Run postalias
  become: yes
  shell: /usr/local/sbin/postalias /etc/aliases

- name: Copy postfix transport file
  become: yes
  copy:
    owner=root
    group=wheel
    mode=644
    src=transport
    dest=/usr/local/etc/postfix/transport

- name: Restart Postfix
  become: yes
  service:
    name=postfix
    state=restarted

- name: Add keep a years maillogs in newsyslog.conf
  become: yes
  lineinfile:
    dest=/etc/newsyslog.conf
    regexp="^/var/log/maillog "
    line="/var/log/maillog                        640  365   *    @T00  JC"
