---
- include_vars: /usr/local/etc/ansible/host_vars/wiki.bornhack.org-passwords.yml

- name: Install mediawiki
  become: yes
  pkgng:
    name=mediawiki126
    state=present

- name: Configure mediawiki
  become: yes
  template:
    src=LocalSettings.php.j2
    dest=/usr/local/www/mediawiki/LocalSettings.php

