---
- name: Install dovecot
  become: yes
  pkgng:
    name=dovecot2
    state=present

- name: Install dovecot-managesieve
  become: yes
  pkgng:
    name=dovecot-pigeonhole
    state=present

- name: Enable dovecot
  become: yes
  service:
    name=dovecot
    enabled=yes

- name: Copy dovecot config
  become: yes
  template:
    src=dovecot.conf.j2
    dest=/usr/local/etc/dovecot/dovecot.conf

- name: Copy dovecot sql config
  become: yes
  template:
    src=dovecot-sql.conf.j2
    dest=/usr/local/etc/dovecot/dovecot-sql.conf
    mode=600

- name: Create virtual mail group
  become: yes
  group:
    name="{{ dovecot_vmail_groupname }}"
    gid="{{ dovecot_vmail_gid}}"
    state=present

- name: Create virtual mail user
  become: yes
  user:
    name={{ dovecot_vmail_username}}
    comment="virtual mail user"
    uid="{{ dovecot_vmail_uid}}"
    group="{{ dovecot_vmail_groupname}}"

- name: Add dovecot.log to syslog.conf
  become: yes
  lineinfile:
    dest=/etc/syslog.conf
    regexp="^local3"
    line="local3.*                                        /var/log/dovecot.log"

- name: Create dovecot.log if it doesn't exist
  become: yes
  file:
    path=/var/log/dovecot.log
    state=touch
    mode=0600

- name: Reload syslogd
  become: yes
  service:
    name=syslogd
    state=reloaded

- name: Add dovecot.log to newsyslog.conf
  become: yes
  lineinfile:
    dest=/etc/newsyslog.conf
    regexp="^/var/log/dovecot.log "
    line="/var/log/dovecot.log                    640  365   *    @T00  JC"

- name: Create mailbox folder
  become: yes
  file:
    path=/usr/mailboxes
    state=directory
    mode=0700
    owner={{ dovecot_vmail_username}}
    group={{ dovecot_vmail_groupname}}

- name: Start dovecot (if not running)
  become: yes
  service:
    name=dovecot
    state=started

- name: Reload dovecot config
  become: yes
  service:
    name=dovecot
    state=reloaded

