---
- name: Configure sshd
  become: yes
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match Group webusers
        ChrootDirectory /usr/webhomes/%uchroot
        PasswordAuthentication no
        ForceCommand internal-sftp
        AllowTcpForwarding no
        AllowAgentForwarding no
        PermitTunnel no
        PermitTTY no
        X11Forwarding no
  notify:
    - restart sshd
