---
- name: Create webusers homedir
  become: yes
  file:
    path=/usr/webhomes
    state=directory
    mode=0755

- name: Create webusers group
  become: yes
  group:
    name=webusers
    state=present

- name: Create chroots
  become: yes
  file:
    path="/usr/webhomes/{{ item.key }}chroot"
    state=directory
    mode=0755
  with_dict: "{{ webusers }}"
  tags:
    - usermanagement

- name: Create web users
  become: yes
  user:
    name="{{ item.key }}"
    comment="{{ item.value.name }}"
    group=webusers
    home="/usr/webhomes/{{ item.key }}chroot/{{ item.key }}"
    shell="/bin/sh"
  with_dict: "{{ webusers }}"
  tags:
    - usermanagement

- name: Create wwwroots
  become: yes
  file:
    path="/usr/webhomes/{{ item.key }}chroot/{{ item.key }}/wwwroot"
    state=directory
    mode=0755
    owner="{{ item.key }}"
    group=webusers
  with_dict: "{{ webusers }}"
  tags:
    - usermanagement

- name: Add SSH keys
  become: yes
  authorized_key:
    user={{ item.key }}
    key="{{ item.value.pubkey }}"
    state=present
    exclusive=yes
  with_dict: "{{ webusers }}"
  tags:
    - usermanagement
