---
- name: Install nginx
  become: yes
  pkgng:
    name=nginx
    state=present

- name: Enable nginx
  become: yes
  service:
    name=nginx
    enabled=yes

- name: Configure nginx
  become: yes
  template:
    src=nginx.conf.j2
    dest=/usr/local/etc/nginx/nginx.conf

- name: Create nginx logfile directory
  become: yes
  file:
    path=/usr/local/www/logs
    state=directory

- name: Start Nginx (if not running)
  become: yes
  service:
    name=nginx
    state=started

- name: Reload nginx config
  become: yes
  service:
    name=nginx
    state=reloaded

