---
blackbox_exporter_modules:
  icmp4-3s-100b:
    prober: "icmp"
    timeout: 3s
    icmp:
      source_ip_address: "127.0.0.1"
      payload_size: 100

  http_2xx:
    prober: "http"
    timeout: "5s"
    http:
      method: "GET"

  smtp_starttls:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^220 ([^ ]+) ESMTP (.+)$"
        - send: "EHLO prober"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober"
        - expect: "^250-AUTH"
        - send: "QUIT"

  dovecot_tls:
    prober: tcp
    timeout: 5s
    tcp:
      tls: true
    tcp:
      query_response:
        - expect: "* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready."

