---
pf_jail_vm_host: True
poudriere_package_set: 'freebsd_11_2_amd64-default'

ezjail_dataset: "zroot/jails"
ezjail_jailstorage_dataset: "zroot/jailstorage"
ezjail_flavourname: "bornhack"
ezjail_flavour_ansible_authorized_keys_file: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLklW3+HXkG0N6M1SG76WSuA4uNbkiVo3bojCox2ogv ansible-generated on ansible2.servers.bornhack.org

zfs_arc_max: "100G"

dns_resolver_ips:
  - "10.0.0.1"
  - "91.239.100.100"
  - "89.233.43.71"

########## snapshots & tykbackup ###############
zfs_periodic_pools:
  - "zroot"

zfs_periodic_datasets_skip:
  - "zroot/reserved"

tykbackup_client: False

########## pf configs ############
pf_main_v4_ip: "5.103.25.42"
pf_jail_nat_ip: "{{ pf_main_v4_ip }}"
pf_jail_nat_range: "10.0.0.0/24"

pf_rdr_rules: |
  # tor jail rdr rules
  rdr on $if inet proto tcp from any to $bluev4 port 2222 -> $dns1v4 port 22
  rdr on $if inet proto tcp from any to $bluev4 port 2223 -> $campftp port 22
  rdr on $if inet proto tcp from any to $bluev4 port 2224 -> $syslog1v4 port 22
  rdr on $if inet proto tcp from any to $bluev4 port 2225 -> $quake3v4 port 22

pf_jail_rules:
  campftp:
    - table: "<campftp>"
      ports:
        - "20"
        - "21"
        - "49152:65535"
      protocols:
        - "tcp"
      clients:
        - "any"
  dns1:
    - table: "<dns1>"
      ports:
        - "53"
      protocols:
        - "tcp"
        - "udp"
      clients:
        - "<dns1clients>"
  syslog1:
    - table: "<syslog1>"
      ports:
        - "514"
      protocols:
        - "udp"
      clients:
        - "<syslog1clients>"

