---
pf_jail_vm_host: True
poudriere_package_set: 'freebsd_11_2_amd64-default'

ezjail_dataset: "zroot/jails"
ezjail_jailstorage_dataset: "zroot/jailstorage"
ezjail_flavourname: "bornhack"
ezjail_flavour_ansible_authorized_keys_file: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLklW3+HXkG0N6M1SG76WSuA4uNbkiVo3bojCox2ogv ansible-generated on ansible2.servers.bornhack.org


########## snapshots & tykbackup ###############
zfs_periodic_pools:
  - "zroot"

zfs_periodic_datasets_skip:
  - "zroot/reserved"

tykbackup_client: False

########## pf configs ############
pf_main_v4_ip: "5.103.25.42"
pf_jail_nat_ip: "{{ pf_main_v4_ip }}"
pf_jail_nat_range: "10.0.0.0/24"

