---
pf_jail_vm_host: True
poudriere_package_set: 'freebsd_12_1_amd64-default'
zfs_arc_max: "128M"

ezjail_dataset: "zroot/usr/jails"
ezjail_jailstorage_dataset: "zroot/usr/jailstorage"
ezjail_flavourname: "bornhack"
ezjail_flavour_ansible_authorized_keys_file: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLklW3+HXkG0N6M1SG76WSuA4uNbkiVo3bojCox2ogv ansible-generated on ansible2.servers.bornhack.org

exporter_exporter_listen_address: "[2a02:2190:f001:1::20]:9999"
node_exporter_listen_address: "127.0.0.1:9100"

########## snapshots & tykbackup ###############
zfs_periodic_pools:
  - "zroot"

zfs_periodic_datasets_skip:
  - "zroot/reserved"

tykbackup_client: False

########## pf configs ############
pf_main_v4_ip: "10.10.1.20"
pf_main_v6_ip: "2a02:2190:f001:1::20"
pf_jail_nat_ip: "{{ pf_main_v4_ip }}"
pf_jail_nat_range: "10.0.0.0/24"
