---
ansible_host: "ezbbgv3dcm6hydlcedsc4funxzfbxr2alivizghtvmboouq4tym2hcyd.onion"
ansible_ssh_common_args: "-o 'ProxyCommand socat STDIO SOCKS4A:127.0.0.1:%h:%p,socksport=9050'"
poudriere_package_set: 'freebsd_12_1_amd64-default'
zfs_arc_max: "128M"

ezjail_dataset: "zroot/usr/jails"
ezjail_jailstorage_dataset: "zroot/usr/jailstorage"
ezjail_flavourname: "bornhack"
ezjail_flavour_ansible_authorized_keys_file: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLklW3+HXkG0N6M1SG76WSuA4uNbkiVo3bojCox2ogv ansible-generated on ansible2.servers.bornhack.org

exporter_exporter_listen_address: "127.0.0.1:9999"
node_exporter_listen_address: "127.0.0.1:9100"


########## tor ##############


hiddenservices:
  - name: "ssh"
    hiddenserviceport: "22 127.0.0.1:22"
    onion_hostname: "ezbbgv3dcm6hydlcedsc4funxzfbxr2alivizghtvmboouq4tym2hcyd.onion"
    authclients:
      - name: "ansible"
        key: "T2MJO5F7I6EW4JNSCEZ6PSWWNO2H5BLMPJSON36ZKHTJAETLJYAQ"
      - name: "tykling"
        key: "SH655NXX2IDMZLDTRSJKEJPF3HZOI6P45B4NS44H7QFLHI5RQ5GA"


########## snapshots & tykbackup ###############


zfs_periodic_pools:
  - "zroot"

zfs_periodic_datasets_skip:
  - "zroot/reserved"

tykbackup_client: False


########## network config ########
network_interfaces:
  - name: "ethernet-upstream"
    description: "ethernet upstream interface, DHCP, v4 only"
    configure: False
    interface: "igb0"
    pf_macro: "eth_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: True


########## pf configs ############
pf_filter_rules:
  - comment: "allow ssh to the firewall itself on the ethernet interface"
    direction: "in"
    interfaces:
      - "$eth_if"
    protocols:
      - "tcp"
    sources:
      - "<allowssh>"
    destinations:
      - "($eth_if)"
    ports:
      - "22"
