---
ansible_host: "ezbbgv3dcm6hydlcedsc4funxzfbxr2alivizghtvmboouq4tym2hcyd.onion"
ansible_ssh_common_args: "-o 'ProxyCommand socat STDIO SOCKS4A:127.0.0.1:%h:%p,socksport=9050'"
poudriere_package_set: 'freebsd_12_1_amd64-default'
zfs_arc_max: "128M"

ezjail_dataset: "zroot/usr/jails"
ezjail_jailstorage_dataset: "zroot/usr/jailstorage"
ezjail_flavourname: "bornhack"
ezjail_flavour_ansible_authorized_keys_file: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLklW3+HXkG0N6M1SG76WSuA4uNbkiVo3bojCox2ogv ansible-generated on ansible2.servers.bornhack.org

exporter_exporter_listen_address: "127.0.0.1:9999"
node_exporter_listen_address: "127.0.0.1:9100"


########## tor ##############


tor_instances:
  main:
    onion_services:
      - name: "ssh"
        comment: "This is the primary container1 SSH onion service, it is running in fib0"
        hidden_service_port: "22 127.0.0.1:22"
        onion_hostname: "ezbbgv3dcm6hydlcedsc4funxzfbxr2alivizghtvmboouq4tym2hcyd.onion"
        auth_clients:
          - name: "ansible2"
            pubkey: "BMED3ZZG3HDN4GPVSFYQ3LXC2WWTMU4Y6XLMN2JIZALRSYMNMN7A"


########## snapshots & tykbackup ###############


zfs_periodic_pools:
  - "zroot"

zfs_periodic_datasets_skip:
  - "zroot/reserved"

tykbackup_client: False


########## network config ########
network_interfaces:
  - name: "ethernet-upstream"
    description: "ethernet upstream interface, DHCP, v4 only"
    configure: False
    interface: "igb0"
    pf_macro: "eth_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: True
    gateway: False
  - name: "telmore-4g-upstream"
    description: "telmore 4g LTE upstream interface, PPP, v4 only"
    configure: False
    interface: "tun0"
    dynamic_ip: True
    pf_macro: "telmore_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: True
    gateway: False
  - name: "telmore2-4g-upstream"
    description: "telmore2 4g LTE upstream interface, PPP, v4 only"
    configure: False
    interface: "tun1"
    dynamic_ip: True
    pf_macro: "telmore2_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: True
    gateway: False


########## pf configs ############
pf_filter_rules:
  - comment: "allow ssh to the firewall itself on the ethernet interface"
    direction: "in"
    interfaces:
      - "$eth_if"
    protocols:
      - "tcp"
    sources:
      - "<allowssh>"
    destinations:
      - "($eth_if)"
    ports:
      - "22"
