---
ansible_host: "ezbbgv3dcm6hydlcedsc4funxzfbxr2alivizghtvmboouq4tym2hcyd.onion"
ansible_ssh_common_args: "-o 'ProxyCommand socat STDIO SOCKS4A:127.0.0.1:%h:%p,socksport=9050'"
poudriere_package_set: 'freebsd_12_1_amd64-default'
zfs_arc_max: "128M"

ezjail_dataset: "zroot/usr/jails"
ezjail_jailstorage_dataset: "zroot/usr/jailstorage"
ezjail_flavourname: "bornhack"
ezjail_flavour_ansible_authorized_keys_file: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLklW3+HXkG0N6M1SG76WSuA4uNbkiVo3bojCox2ogv ansible-generated on ansible2.servers.bornhack.org

exporter_exporter_listen_address: "127.0.0.1:9999"
node_exporter_listen_address: "127.0.0.1:9100"

certgrinder_certgrinderd_command: "ssh certgrinderd@h6idafowi3v2uxcfo72rplldhulhw4voh2tthfcup37az3k7ju7bfqqd.onion -T -- --config-file /home/certgrinderd/certgrinderd.conf"

########## snapshots & tykbackup ###############


zfs_periodic_pools:
  - "zroot"

zfs_periodic_datasets_skip:
  - "zroot/reserved"

tykbackup_client: False


########## network config ########
network_interfaces:
  - name: "ethernet-upstream"
    description: "ethernet upstream interface, DHCP, v4 only"
    configure: False
    interface: "igb0"
    pf_macro: "eth_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: True
    gateway: False
  - name: "telmore-4g-upstream"
    description: "telmore 4g LTE upstream interface, PPP, v4 only"
    configure: False
    interface: "tun0"
    dynamic_ip: True
    pf_macro: "telmore_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: True
    gateway: False
  - name: "telmore2-4g-upstream"
    description: "telmore2 4g LTE upstream interface, PPP, v4 only"
    configure: False
    interface: "tun1"
    dynamic_ip: True
    pf_macro: "telmore2_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: True
    gateway: False


########## pf configs ############
pf_filter_rules:
  - comment: "allow ssh to the firewall itself on the ethernet interface"
    direction: "in"
    interfaces:
      - "$eth_if"
    protocols:
      - "tcp"
    sources:
      - "<allowssh>"
    destinations:
      - "($eth_if)"
    ports:
      - "22"


tor_instances:
  main:
    onion_services:
      - name: "container1"
        comment: "This is the primary container1 onion service, it is running in fib0"
        hidden_service_ports:
          - "22 127.0.0.1:22"
          - "9999 127.0.0.1:9999"
        onion_hostname: "ezbbgv3dcm6hydlcedsc4funxzfbxr2alivizghtvmboouq4tym2hcyd.onion"
        auth_clients:
          - name: "ansible2"
            pubkey: "BMED3ZZG3HDN4GPVSFYQ3LXC2WWTMU4Y6XLMN2JIZALRSYMNMN7A"
          - name: "tyk_t590_laptop"
            pubkey: "NUUW6MAVWWNQWBHE3JGHTT675N3U53KNVWLHKYTAFKYQMXO3EAVQ"
          - name: "prometheus1"
            pubkey: "ZQQ2HH377XRKJLKU6BKH4ZVDIIJ6IZCEOUPTVQKVNLHVX2LOFZ2A"
          - name: "fj_guide3"
            pubkey: "MDSAFUANUEIB4PYLJOUJAAHLGDQNBIBMKJL2F4ISILSTDZG2JUCA"
    onion_client_auths:
      - name: "certgrinder1_ssh"
        onion: "h6idafowi3v2uxcfo72rplldhulhw4voh2tthfcup37az3k7ju7bfqqd"
        privkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30636132316230613537323739643138636561643436656537306436313830666637373439323065
          3439326361656265343661363932376536663565316365620a653037613666646466616563333965
          62396436383361393532323864663131333161393832653765313632313232336564303162306166
          6364353339373330650a303634643063316330383862616233366138663534343766393132316363
          38636530666539393565633031336636323265356634383030353035323431616132393532366264
          36383037313039343265336664353833366461396436386661366331333433353732636565613230
          633762613937626438366535643261356535
  telmore:
    fib: 1
    disable_socks: True
    syslog_identity: "telmore"
    onion_services:
      - name: "sshtelmore"
        comment: "This is the backup SSH onion service running on the Telmore LTE modem"
        hidden_service_ports:
          - "22 127.0.0.1:22"
        onion_hostname: "d5zz2ohagtjfof52l6zmcoj7vc4g3b4zyigt7q7sz6qxwhynhmmipgqd.onion"
        auth_clients:
          - name: "ansible2"
            pubkey: "BMED3ZZG3HDN4GPVSFYQ3LXC2WWTMU4Y6XLMN2JIZALRSYMNMN7A"
          - name: "tyk_t590_laptop"
            pubkey: "NUUW6MAVWWNQWBHE3JGHTT675N3U53KNVWLHKYTAFKYQMXO3EAVQ"
          - name: "fj_guide3"
            pubkey: "MDSAFUANUEIB4PYLJOUJAAHLGDQNBIBMKJL2F4ISILSTDZG2JUCA"
  telmore2:
    fib: 2
    disable_socks: True
    syslog_identity: "telmore2"
    onion_services:
      - name: "sshtelmore2"
        comment: "This is the backup SSH onion service running on the Telmore2 LTE modem"
        hidden_service_ports:
          - "22 127.0.0.1:22"
        onion_hostname: "qzfrijhdxs7ezqjl6u32hx4stsdq75atm2b36gmuz2v4sijmzwdelhyd.onion"
        auth_clients:
          - name: "ansible2"
            pubkey: "BMED3ZZG3HDN4GPVSFYQ3LXC2WWTMU4Y6XLMN2JIZALRSYMNMN7A"
          - name: "tyk_t590_laptop"
            pubkey: "NUUW6MAVWWNQWBHE3JGHTT675N3U53KNVWLHKYTAFKYQMXO3EAVQ"
          - name: "fj_guide3"
            pubkey: "MDSAFUANUEIB4PYLJOUJAAHLGDQNBIBMKJL2F4ISILSTDZG2JUCA"

mobile_modem_devices:
  - "/dev/modem-huawei-control"
  - "/dev/modem-quectel-control"


ppp_profiles:
  - name: "ppp_telmore_quectel"
    comment: "run ppp for telmore isp, quectel modem"
    command: "/usr/sbin/ppp -foreground -unit0 telmore_quectel"
    user: "0"
    priority: "1"
  - name: "ppp_telmore_huawei"
    comment: "run ppp for telmore isp, huawei modem"
    command: "/usr/sbin/ppp -foreground -unit1 telmore_huawei"
    user: "0"
    priority: "1"

supervisord_custom_jobs:
  - name: "videouploader"
    comment: "run videouploader.sh to upload videos to people.bornhack.org"
    command: "/usr/home/videouploader/videouploader.sh"
    user: "videouploader"
    priority: "1"
