---
dovecot_postgres_host: 10.0.0.3
dovecot_postgres_dbname: bornhackmail
dovecot_postgres_user: dovecot
dovecot_vmail_username: vmail
dovecot_vmail_uid: 10000
dovecot_vmail_groupname: vmail
dovecot_vmail_gid: 10000

certgrinder_hostname_sets:
 - "imap.bornhack.org"

certgrinder_post_renew_hooks:
  - "/usr/sbin/service nginx reload"
  - "/usr/sbin/service dovecot reload"

