---
dovecot_postgres_host: 10.0.0.3
dovecot_postgres_dbname: bornhackmail
dovecot_postgres_user: dovecot
dovecot_vmail_username: vmail
dovecot_vmail_uid: 10000
dovecot_vmail_groupname: vmail
dovecot_vmail_gid: 10000

certgrinder_hostname_sets:
 - "imap2.servers.bornhack.org,imap.bornhack.org"

nginx_locationslash:
  location /.well-known/acme-challenge/ {
        return 301 {{ certgrinder_redirect_url }}$request_uri;
  }
  location / {
        return 301 https://bornhack.dk;
  }

