---
poudriere_package_set: 'freebsd_13_0_amd64-default'


########## snapshots & tykbackup ###############

zfs_periodic_pools:
  - "zroot"

zfs_periodic_datasets_skip:
  - "zroot/reserved"

tykbackup_client: False


########## network config ########
network_interfaces:
  - name: "ethernet-upstream"
    description: "ethernet upstream interface, 85.209.118.128/28 & 2a09:94c4:55d1:7680::/64"
    configure: True
    interface: "em0"
    v4net: "85.209.118.128/28"
    v6net: "2a09:94c4:55d1:7680::/64"
    pf_macro: "ext_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: True
    ips:
      nuc1:
        v4ip: "85.209.118.130"
        v6ip: "2a09:94c4:55d1:7680::82"

  - name: "bridge-routed"
    description: "bridge interface for the routed networks 85.209.118.160/29 & 2a09:94c4:55d1:7682::/64"
    configure: True
    interface: "bridge0"
    cloned: True
    v4net: "85.209.118.160/29"
    v6net: "2a09:94c4:55d1:7682::/64"
    pf_macro: "bridge_routed_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: False
    pf_routing: True
    ips:
      nuc1:
        v4ip: "85.209.118.161"
        v6ip: "2a09:94c4:55d1:7682::1"

  - name: "bridge-rfc1918"
    description: "bridge interface for the rfc1918 network 10.1.0.0/24 & 2a09:94c4:55d1:76A0::/64"
    configure: True
    interface: "bridge1"
    cloned: True
    v4net: "10.1.0.0/24"
    v6net: "2a09:94c4:55d1:76A0::/64"
    pf_macro: "bridge_rfc1918_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: False
    pf_routing: True
    ips:
      nuc1:
        v4ip: "10.1.0.1"
        v6ip: "2a09:94c4:55d1:76A0::1"

  - name: "epair1a"
    description: "vnet interface for dns1.servers.bornhack.org"
    configure: False
    interface: "epair1a"
    pf_macro: "dns1_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: False
    pf_routing: True

  - name: "epair2a"
    description: "vnet interface for syslog1.servers.bornhack.org"
    configure: False
    interface: "epair2a"
    pf_macro: "syslog1_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: False
    pf_routing: True

  - name: "epair3a"
    description: "vnet interface for postgres1.servers.bornhack.org"
    configure: False
    interface: "epair3a"
    pf_macro: "postgres1_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: False
    pf_routing: True

  - name: "epair4a"
    description: "vnet interface for webproxy3.servers.bornhack.org"
    configure: False
    interface: "epair4a"
    pf_macro: "webproxy3_if"
    pf_scrub: True
    pf_sync: False
    pf_carp: False
    pf_upstream: False
    pf_routing: True

static_routes:
  - name: "dgw_ipv4"
    route: "-inet default 85.209.118.129"
    description: "Default gateway for ipv4"
  - name: "dgw_ipv6"
    route: "-inet6 default 2a09:94c4:55d1:7680::81"
    description: "Default gateway for ipv6"

########## pf configs ############

pf_gateway: True

pf_nat_rules: |
  nat on $ext_if from ($bridge_rfc1918_if:network) to any -> ($ext_if)

pf_filter_rules:
  - comment: "allow ssh to the firewall itself on the upstream interface"
    direction: "in"
    interfaces:
      - "$ext_if"
    protocols:
      - "tcp"
    sources:
      - "<allowssh>"
    destinations:
      - "($ext_if)"
    ports:
      - "22"

########## jails ############

ezjail_dataset: "zroot/usr/jails"
ezjail_jailstorage_dataset: "zroot/usr/jailstorage"
ezjail_flavourname: "bornhack"
ezjail_flavour_ansible_authorized_keys_file: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICLklW3+HXkG0N6M1SG76WSuA4uNbkiVo3bojCox2ogv ansible-generated on ansible2.servers.bornhack.org

jail_root: "/usr/jails"
jails:
  - hostname: "dns1.servers.bornhack.org"
    interfaces:
      - epair: 1
        bridge: "bridge1" # rfc1918
        ifconfig_inet: "10.1.0.2/24"
        ifconfig_inet6: "2a09:94c4:55d1:76A0::2/64"
    routes:
      - "-inet default 10.1.0.1"
      - "-inet6 default 2a09:94c4:55d1:76A0::1"

  - hostname: "syslog1.servers.bornhack.org"
    interfaces:
      - epair: 2
        bridge: "bridge1" # rfc1918
        ifconfig_inet: "10.1.0.3/24"
        ifconfig_inet6: "2a09:94c4:55d1:76A0::3/64"
    routes:
      - "-inet default 10.1.0.1"
      - "-inet6 default 2a09:94c4:55d1:76A0::1"

  - hostname: "postgres1.servers.bornhack.org"
    interfaces:
      - epair: 3
        bridge: "bridge1" # rfc1918
        ifconfig_inet: "10.1.0.4/24"
        ifconfig_inet6: "2a09:94c4:55d1:76A0::4/64"
    routes:
      - "-inet default 10.1.0.1"
      - "-inet6 default 2a09:94c4:55d1:76A0::1"

  - hostname: "webproxy3.servers.bornhack.org"
    interfaces:
      - epair: 4
        bridge: "bridge0" # routed
        ifconfig_inet: "85.209.118.162/29"
        ifconfig_inet6: "2a09:94c4:55d1:7682::162/64"
    routes:
      - "-inet default 85.209.118.161"
      - "-inet6 default 2a09:94c4:55d1:7682::1"
