---
prometheus_monitor_name: "prometheus1"
prometheus_external_url: "https://prometheus.bornhack.org"

prometheus_alertmanager_configs:
  - scheme: "https"
    static_configs:
      - targets:
        - "alertmanager.bornhack.org:443"

prometheus_alertmanager_rules:
  - name: "bornhack-certificate-group"
    rules:
      - alert: "https_certificate_too_old"
        expr: "((probe_ssl_earliest_cert_expiry{job='bornhack-http-services'} - time()) / 60 / 60 / 24) < 29"
        for: "10m"
        annotations:
          summary: "The target certificate expires in 28 days or less, check certgrinder.log"

prometheus_scrape_configs:
  - name: 'bornhack-http-services'
    scheme: 'http'
    scrape_interval: '15s'
    metrics_path: "/probe"
    params:
      module:
        - "http_2xx"
    targets:
      - "bornhack.dk"
      - "wwwstaging.bornhack.org"
      - "mail.bornhack.org"
      - "people.bornhack.org"
    relabel_configs:
      - source_labels:
          - '__address__'
        target_label: '__param_target'
      - source_labels:
          - '__param_target'
        target_label: 'instance'
      - target_label: '__address__'
        replacement: 'blackbox1.servers.bornhack.org:9115'
  - name: 'bornhack-imap-service'
    scheme: 'http'
    scrape_interval: '15s'
    metrics_path: "/probe"
    params:
      module:
        - "dovecot_tls"
    targets:
      - "imap.bornhack.org:993"
    relabel_configs:
      - source_labels:
          - '__address__'
        target_label: '__param_target'
      - source_labels:
          - '__param_target'
        target_label: 'instance'
      - target_label: '__address__'
        replacement: 'blackbox1.servers.bornhack.org:9115'
  - name: 'bornhack-smtp-service'
    scheme: 'http'
    scrape_interval: '15s'
    metrics_path: "/probe"
    params:
      module:
        - "smtp_starttls"
    targets:
      - "mail.bornhack.org:587"
    relabel_configs:
      - source_labels:
          - '__address__'
        target_label: '__param_target'
      - source_labels:
          - '__param_target'
        target_label: 'instance'
      - target_label: '__address__'
        replacement: 'blackbox1.servers.bornhack.org:9115'

