---
prometheus_monitor_name: "prometheus1"
prometheus_external_url: "https://prometheus.bornhack.org"

prometheus_alertmanager_configs:
  - scheme: "https"
    static_configs:
      - targets:
        - "alertmanager.bornhack.org:443"

prometheus_alertmanager_rules:
  - name: "bornhack-probe-group"
    rules:
      - alert: "probe_not_up"
        expr: "up == 0"
        for: "10m"
        annotations:
          summary: "One or more probes are not up. Services are probably not affected, check if blackbox_exporter is running!"
      - alert: "probe_unsuccessful"
        expr: "probe_success == 0"
        for: "10m"
        annotations:
          summary: "One or more probes failed. Check the affected services!"
  - name: "bornhack-certificate-group"
    rules:
      - alert: "https_certificate_too_old"
        expr: "((probe_ssl_earliest_cert_expiry - time()) / 60 / 60 / 24) < 29"
        for: "10m"
        annotations:
          summary: "The target certificate expires in 28 days or less, check certgrinder.log"

prometheus_scrape_configs:
  - name: 'bornhack-http-services'
    scheme: 'http'
    scrape_interval: '15s'
    metrics_path: "/probe"
    params:
      module:
        - "http_2xx"
    targets:
      - "bornhack.dk"
      - "wwwstaging.bornhack.org"
      - "mail.bornhack.org"
      - "people.bornhack.org/tyk"
    relabel_configs:
      - source_labels:
          - '__address__'
        target_label: '__param_target'
      - source_labels:
          - '__param_target'
        target_label: 'instance'
      - target_label: '__address__'
        replacement: 'blackbox1.servers.bornhack.org:9115'
  - name: 'bornhack-imap-service'
    scheme: 'http'
    scrape_interval: '15s'
    metrics_path: "/probe"
    params:
      module:
        - "dovecot_tls"
    targets:
      - "imap.bornhack.org:993"
    relabel_configs:
      - source_labels:
          - '__address__'
        target_label: '__param_target'
      - source_labels:
          - '__param_target'
        target_label: 'instance'
      - target_label: '__address__'
        replacement: 'blackbox1.servers.bornhack.org:9115'
  - name: 'bornhack-smtp-service'
    scheme: 'http'
    scrape_interval: '15s'
    metrics_path: "/probe"
    params:
      module:
        - "smtp_starttls"
    targets:
      - "mail.bornhack.org:587"
    relabel_configs:
      - source_labels:
          - '__address__'
        target_label: '__param_target'
      - source_labels:
          - '__param_target'
        target_label: 'instance'
      - target_label: '__address__'
        replacement: 'blackbox1.servers.bornhack.org:9115'

  - name: "expexp"
    scheme: "https"
    scrape_interval: "10s"
    targets:
      - "alertmanager1.servers.bornhack.org:9999"
      - "ansible2.servers.bornhack.org:9999"
      - "blackbox1.servers.bornhack.org:9999"
      - "certgrinder1.servers.bornhack.org:9999"
      - "grafana1.servers.bornhack.org:9999"
      - "imap2.servers.bornhack.org:9999"
      - "mail.bornhack.org:9999"
      - "people2.servers.bornhack.org:9999"
      - "prometheus1.servers.bornhack.org:9999"
      - "staging3.servers.bornhack.org:9999"
      - "tor2.servers.bornhack.org:9999"
      - "webproxy2.servers.bornhack.org:9999"
      - "wwwprod3.servers.bornhack.org:9999"

  - name: "node_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "node_exporter"
    targets:
      - "alertmanager1.servers.bornhack.org:9999"
      - "ansible2.servers.bornhack.org:9999"
      - "blackbox1.servers.bornhack.org:9999"
      - "certgrinder1.servers.bornhack.org:9999"
      - "grafana1.servers.bornhack.org:9999"
      - "imap2.servers.bornhack.org:9999"
      - "mail.bornhack.org:9999"
      - "people2.servers.bornhack.org:9999"
      - "prometheus1.servers.bornhack.org:9999"
      - "staging3.servers.bornhack.org:9999"
      - "tor2.servers.bornhack.org:9999"
      - "webproxy2.servers.bornhack.org:9999"
      - "wwwprod3.servers.bornhack.org:9999"

  - name: "uwsgi_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "uwsgi_exporter"
    targets:
      - "staging3.servers.bornhack.org:9999"
      - "wwwprod3.servers.bornhack.org:9999"

  - name: "nginx_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "nginx_exporter"
    targets:
      - "alertmanager1.servers.bornhack.org:9999"
      - "blackbox1.servers.bornhack.org:9999"
      - "certgrinder1.servers.bornhack.org:9999"
      - "grafana1.servers.bornhack.org:9999"
      - "people2.servers.bornhack.org:9999"
      - "prometheus1.servers.bornhack.org:9999"
      - "staging3.servers.bornhack.org:9999"
      - "webproxy2.servers.bornhack.org:9999"
      - "wwwprod3.servers.bornhack.org:9999"

  - name: "bind_exporter"
    scheme: "https"
    scrape_interval: "10s"
    metrics_path: "/proxy"
    params:
      module:
        - "bind_exporter"
    targets:
      - "certgrinder1.servers.bornhack.org:9999"

