---
nginx_proxy: True
nginx_cache: True
nginx_cache_inactive: "24h"

vhosts:
  webproxy3_servers_bornhack_dk:
    vhost_v6ip: "2a09:94c4:55d1:7682::162"
    hostnames:
      - webproxy3.servers.bornhack.org
    default_vhost: True
    locationslash: |
      location /goaccess {
          allow 2a01:3a0:1:1900:10::27;
          deny all;
          alias /usr/local/www/goaccess;
      }
      location = /stub_status {
          stub_status;
          allow 127.0.0.1;
          allow ::1;
          allow 2a09:94c4:55d1:7682::162;
          allow 85.209.118.162;
          deny all;
      }
      location / {
          return 301 https://bornhack.dk/;
      }

certgrinder_hostname_sets:
  - "webproxy3.servers.bornhack.org"

goaccess_exclude_ips:
  - "2a01:3a0:1:1900:10::30"

nginx_exporter_uri: "https://webproxy3.servers.bornhack.org/stub_status"
