nginx_proxy: True
vhosts:
  webproxy_bong_bornhack_dk:
    vhost_v6ip: "2a01:3a0:1:1900:85:235:250:89"
    hostnames:
      - webproxy-bong.bornhack.org
    default_vhost: True
    locationslash: |
      return 301 https://bornhack.dk/;

  bornhack_dk:
    vhost_v6ip: "2a01:3a0:1:1900:81::1"
    hostnames:
      - bornhack.dk
      - www.bornhack.dk
    locationslash: |
      location / {
          proxy_pass http://wwwprod2.servers.bornhack.org:80;
      }

  wiki_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::2"
    hostnames:
      - wiki.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.11:80;
      }

  wwwstaging_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::3"
    hostnames:
      - wwwstaging.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://staging2.servers.bornhack.org:80;
      }
  minutes_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::4"
    hostnames:
      - minutes.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.15:80;
      }
  nuntio_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::5"
    hostnames:
      - nuntio.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.18:8080;
      }

