---
nginx_proxy: True
nginx_cache: True
nginx_cache_inactive: "24h"

vhosts:
  webproxy2_servers_bornhack_dk:
    vhost_v6ip: "2a01:3a0:1:1900:85:235:250:91"
    hostnames:
      - webproxy2.servers.bornhack.org
    default_vhost: True
    locationslash: |
      location /goaccess {
          allow 2a01:3a0:1:1900:10::27;
          deny all;
          alias /usr/local/www/goaccess;
      }
      location = /stub_status {
          stub_status;
          allow 127.0.0.1;
          allow ::1;
          allow 2a01:3a0:1:1900:85:235:250:91;
          allow 85.235.250.91;
          deny all;
      }
      location / {
          return 301 https://bornhack.dk/;
      }

  bornhack_dk:
    vhost_v6ip: "2a01:3a0:1:1900:81::1"
    hostnames:
      - bornhack.dk
      - www.bornhack.dk
    locationslash: |
      location / {
          proxy_pass http://wwwprod3.servers.bornhack.org:80;
          more_set_headers        "X-Secret-Token: zG6dniE1yCWuB0O6QxQwyATN3sB0YfUU";
      }

  coinifycallback_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::6"
    hostnames:
      - coinifycallback.bornhack.org
    locationslash: |
      location ~ /shop/orders/(?<orderid>[0-9]+)/pay/blockchain/callback/ {
          proxy_set_header        Host bornhack.dk;
          proxy_pass http://wwwprod3.servers.bornhack.org:80;
      }
      location / {
        return 301 https://bornhack.dk/;
      }

  wwwstaging_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::3"
    hostnames:
      - wwwstaging.bornhack.org
    locationslash: |
      # kortforsyningen tile caching
      location /maps/kfproxy/ {
        proxy_cache my_cache;
        proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        proxy_cache_valid any 24h;
        proxy_pass http://staging3.servers.bornhack.org:80;
      }
      location / {
          proxy_pass http://staging3.servers.bornhack.org:80;
      }

  minutes_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::4"
    hostnames:
      - minutes.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.15:80;
      }

  nuntio_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::5"
    hostnames:
      - nuntio.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.18:8080;
      }

  live_bornhack_dk:
    vhost_v6ip: "2a01:3a0:1:1900:81::7"
    hostnames:
      - live.bornhack.dk
    locationslash: |
      location / {
          return 302 https://www.youtube.com/c/BornHack/live;
      }

  prometheus_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::8"
    hostnames:
      - prometheus.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.28:80;
      }

  alertmanager_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::9"
    hostnames:
      - alertmanager.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.29:80;
      }

  blackbox_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::10"
    hostnames:
      - blackbox.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.30:80;
      }

  grafana_bornhack_org:
    vhost_v6ip: "2a01:3a0:1:1900:81::11"
    hostnames:
      - grafana.bornhack.org
    locationslash: |
      location / {
          proxy_pass http://10.0.0.31:80;
      }


certgrinder_hostname_sets:
  - "webproxy2.servers.bornhack.org"
  - "bornhack.dk,www.bornhack.dk"
  - "wwwstaging.bornhack.org"
  - "minutes.bornhack.org"
  - "nuntio.bornhack.org"
  - "coinifycallback.bornhack.org"
  - "live.bornhack.dk"
  - "prometheus.bornhack.org"
  - "alertmanager.bornhack.org"
  - "blackbox.bornhack.org"
  - "grafana.bornhack.org"

certgrinder_post_renew_hooks:
  - "/usr/sbin/service nginx reload"

certgrinder_bind_ip: "2a01:3a0:1:1900:85:235:250:91"

goaccess_exclude_ips:
  - "2a01:3a0:1:1900:10::30"

nginx_exporter_uri: "https://webproxy2.servers.bornhack.org/stub_status"

