nginx_proxy: True
nginx_v4_proxy_ip: "85.235.250.91"

vhosts:
  webproxy2_servers_bornhack_dk:
    vhost_v6ip: "2a01:3a0:1:1900:85:235:250:91"
    hostnames:
      - webproxy2.servers.bornhack.org
    default_vhost: True
    locationslash: |
      return 301 https://bornhack.dk/;

certgrinder_hostname_sets:
  - "webproxy2.servers.bornhack.org"
certgrinder_post_renew_hooks:
  - "/usr/sbin/service nginx reload"

certgrinder_bind_ip: "2a01:3a0:1:1900:85:235:250:91"

