---
django_root: "{{ django_checkout_path }}/src"
django_mainapp: "bornhack"
django_allowed_hostnames: "['bornhack.dk','www.bornhack.dk','nclpuewtqbrtgnugfquprohygp2ni2idinfrbmiptxrp6d6uvtctpyid.onion']"
django_debug: 'False'
django_github_repo_url: "https://github.com/bornhack/bornhack-website"
django_pip_requirements_path: "{{ django_root }}/requirements/production.txt"
django_postgres_user: "bornhackdk"
django_postgres_host: "10.0.0.3"
django_postgres_dbname: "bornhackdkdb"
django_email_realworld: True
django_email_user: "noreply@bornhack.org"
django_email_port: "587"
django_email_host: "mail.bornhack.org"
django_email_from: "info@bornhack.dk"
django_media_root: "/storage/django_media_root"
django_media_root_subdirs:
  - "proforma_invoices"
  - "invoices"
  - "creditnotes"
  - "public"

django_extra_os_dependencies:
  - "graphics/jpeg-turbo"
  - "converters/wkhtmltopdf"
  - "x11-fonts/webfonts"
  - "graphics/gdal"
  - "graphics/geos"
  - "textproc/libxslt"

django_archive_email: "mailarchive@bornhack.org"

django_admins: |
  (
      ('bornhack sysadm', 'sysadm@bornhack.org'),
  )

django_timezone: 'Europe/Copenhagen'

supervisord_extra_programs:
  - name: "redis"
    comment: "run redis"
    command: "/usr/local/bin/redis-server /usr/local/etc/redis.conf"
    user: "535" # 535 is the redis uid on freebsd
    priority: "1"

  - name: "invoiceworker"
    comment: "run invoiceworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 30 shop.invoiceworker"
    user: "www"
    priority: "4"

  - name: "outgoingemailworker"
    comment: "run outgoingemailworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 30 utils.outgoingemailworker"
    user: "www"
    priority: "4"

  - name: "ircworker"
    comment: "run ircworker"
    command: "{{ django_virtualenv_path }}/bin/python -u {{ django_root }}/manage.py run_managepy_worker --sleep 10 ircbot.ircworker"
    user: "www"
    priority: "4"


uwsgi_processes: 20

pdf_archive_path: '/storage/pdf_archive/'
pdf_letterhead_filename: "bornhack-2020_letterhead.pdf"
iban: "DK0398600000747866"
swiftbic: "FOSPDK21"
regno: 9860
accountno: 747866
bank_name: "Folke Sparekassen"

django_ircbot_nickname: "BornHack"
django_ircbot_server: "irc.baconsvin.org"
django_ircbot_public_channel: "#bornhack"
django_ircbot_volunteer_channel: "#bornhack.org"
django_ircbot_nickserv_mask: "NickServ@services.baconsvin.org"
django_ircbot_chanserv_mask: "ChanServ@services.baconsvin.org"
django_ircbot_nickserv_email: "ircbot@bornhack.org"

coinify_callback_hostname: "coinifycallback.bornhack.org"

django_channels_layer_redis: True
django_channels_backend: "channels_redis.core.RedisChannelLayer"

django_accountingsystem_email: "866bilag1182644@e-conomic.dk"
django_economyteam_email: "economy-team@bornhack.org"

backoffice_proxy_urls: |
  {
      "webstats-2016": ("Webproxy stats 2016", "https://webproxy2.servers.bornhack.org/goaccess/2016.html"),
      "webstats-2017": ("Webproxy stats 2017", "https://webproxy2.servers.bornhack.org/goaccess/2017.html"),
      "webstats-2018": ("Webproxy stats 2018", "https://webproxy2.servers.bornhack.org/goaccess/2018.html"),
      "webstats-2019": ("Webproxy stats 2019", "https://webproxy2.servers.bornhack.org/goaccess/2019.html"),
      "webstats-2020": ("Webproxy stats 2020", "https://webproxy2.servers.bornhack.org/goaccess/2020.html"),
  }
