---
- name: Install mailman
  become: yes
  pkgng:
    name=mailman
    state=present

- name: Enable mailman
  become: yes
  service:
    name=mailman
    enabled=yes

- name: Configure mailman DEFAULT_EMAIL_HOST
  become: yes
  lineinfile:
    dest=/usr/local/mailman/Mailman/Defaults.py
    regexp="^DEFAULT_EMAIL_HOST = "
    line="DEFAULT_EMAIL_HOST = '{{ postfix_virtual_alias_domain }}'"

- name: Configure mailman DEFAULT_URL_HOST
  become: yes
  lineinfile:
    dest=/usr/local/mailman/Mailman/Defaults.py
    regexp="^DEFAULT_URL_HOST = "
    line="DEFAULT_URL_HOST = '{{ ansible_nodename }}'"

- name: Configure mailman DEFAULT_URL_PATTERN
  become: yes
  lineinfile:
    dest=/usr/local/mailman/Mailman/Defaults.py
    regexp="^DEFAULT_URL_PATTERN = "
    line="DEFAULT_URL_PATTERN = 'https://%s/mailman/'"

- name: Fix permissions on mailman private archive dir
  become: yes
  file:
    path=/usr/local/mailman/archives/private
    state=directory
    mode=02770

- name: generate mailman list password
  shell: "openssl rand -base64 33 | tr -d '='"
  args:
    creates: "/usr/local/mailman/lists/mailman"
  register: password

- name: Create mailman mailing lists
  become: yes
  shell: "/usr/local/mailman/bin/newlist -a mailman {{ mailman_list_owner }} {{ password.stdout }}"
  args:
    creates: "/usr/local/mailman/lists/mailman"

- name: Create aliases for mailinglists
  become: yes
  blockinfile:
    create: yes
    dest: /usr/local/etc/postfix/mailman-virtual
    marker: "# {mark} ANSIBLE MANAGED BLOCK mailman"
    content: |
      ## mailman mailing list
      mailman@{{ postfix_virtual_alias_domain }}:              "|/usr/local/mailman/mail/mailman post mailman"
      mailman-admin@{{ postfix_virtual_alias_domain }}:        "|/usr/local/mailman/mail/mailman admin mailman"
      mailman-bounces@{{ postfix_virtual_alias_domain }}:      "|/usr/local/mailman/mail/mailman bounces mailman"
      mailman-confirm@{{ postfix_virtual_alias_domain }}:      "|/usr/local/mailman/mail/mailman confirm mailman"
      mailman-join@{{ postfix_virtual_alias_domain }}:         "|/usr/local/mailman/mail/mailman join mailman"
      mailman-leave@{{ postfix_virtual_alias_domain }}:        "|/usr/local/mailman/mail/mailman leave mailman"
      mailman-owner@{{ postfix_virtual_alias_domain }}:        "|/usr/local/mailman/mail/mailman owner mailman"
      mailman-request@{{ postfix_virtual_alias_domain }}:      "|/usr/local/mailman/mail/mailman request mailman"
      mailman-subscribe@{{ postfix_virtual_alias_domain }}:    "|/usr/local/mailman/mail/mailman subscribe mailman"
      mailman-unsubscribe@{{ postfix_virtual_alias_domain }}:  "|/usr/local/mailman/mail/mailman unsubscribe mailman"

- name: Start mailman
  become: yes
  service:
    name=mailman
    state=started

- name: generate mailinglist passwords
  shell: "openssl rand -base64 33 | tr -d '='"
  args:
    creates: "/usr/local/mailman/lists/{{ item.key }}"
  register: passwords
  with_dict: "{{ lists }}"

- name: Create mailinglists
  become: yes
  shell: "/usr/local/mailman/bin/newlist -a {{ item.0 }} {{ lists[item.0] }} {{ item.1.stdout }}"
  args:
    creates: "/usr/local/mailman/lists/{{ item.0 }}"
  with_together:
    - "{{ lists }}"
    - "{{ passwords.results }}"

- name: Create aliases for mailinglists
  become: yes
  blockinfile:
    create: yes
    dest: /usr/local/etc/postfix/mailman-virtual
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{item.key}}"
    content: |
      ## {{ item.key }} mailing list
      {{ item.key }}@{{ postfix_virtual_alias_domain }}:              "|/usr/local/mailman/mail/mailman post {{ item.key }}"
      {{ item.key }}-admin@{{ postfix_virtual_alias_domain }}:        "|/usr/local/mailman/mail/mailman admin {{ item.key }}"
      {{ item.key }}-bounces@{{ postfix_virtual_alias_domain }}:      "|/usr/local/mailman/mail/mailman bounces {{ item.key }}"
      {{ item.key }}-confirm@{{ postfix_virtual_alias_domain }}:      "|/usr/local/mailman/mail/mailman confirm {{ item.key }}"
      {{ item.key }}-join@{{ postfix_virtual_alias_domain }}:         "|/usr/local/mailman/mail/mailman join {{ item.key }}"
      {{ item.key }}-leave@{{ postfix_virtual_alias_domain }}:        "|/usr/local/mailman/mail/mailman leave {{ item.key }}"
      {{ item.key }}-owner@{{ postfix_virtual_alias_domain }}:        "|/usr/local/mailman/mail/mailman owner {{ item.key }}"
      {{ item.key }}-request@{{ postfix_virtual_alias_domain }}:      "|/usr/local/mailman/mail/mailman request {{ item.key }}"
      {{ item.key }}-subscribe@{{ postfix_virtual_alias_domain }}:    "|/usr/local/mailman/mail/mailman subscribe {{ item.key }}"
      {{ item.key }}-unsubscribe@{{ postfix_virtual_alias_domain }}:  "|/usr/local/mailman/mail/mailman unsubscribe {{ item.key }}"
  with_dict: "{{ lists }}"

- name: Reload Postfix
  become: yes
  service:
    name=postfix
    state=reloaded
