---
- name: Install postfix
  become: yes
  pkgng:
    name=postfix
    state=present

- name: Enable postfix
  become: yes
  service:
    name=postfix
    enabled=yes

- name: Copy postfix main.cf
  become: yes
  template:
    src=main.cf.j2
    dest=/usr/local/etc/postfix/main.cf

- name: Run postalias
  become: yes
  shell: /usr/local/sbin/postalias /etc/aliases

- name: Copy postfix virtual file
  become: yes
  copy:
    owner=root
    group=wheel
    mode=644
    src=virtual
    dest=/usr/local/etc/postfix/virtual

- name: Restart Postfix
  become: yes
  service:
    name=postfix
    state=restarted
