---
- name: Copy installdhparam script
  become: yes
  copy:
    src=roles/nginx_proxy/files/installdhparam.sh
    dest=/usr/local/bin/installdhparam
    owner=root
    group=wheel
    mode=0700

- name: Copy dhparamgen script
  become: yes
  copy:
    src=roles/nginx_proxy/files/dhparamgen.sh
    dest=/usr/local/bin/dhparamgen
    owner=root
    group=wheel
    mode=0700

- name: Copy rc.d script for dhparamgen
  become: yes
  copy:
    src=roles/nginx_proxy/files/dhparamgen.rc.d
    dest=/usr/local/etc/rc.d/dhparamgen
    owner=root
    group=wheel
    mode=0700

- name: Enable dhparamgen
  become: yes
  service:
    name=dhparamgen
    enabled=yes

- name: Set dhparamgen_opensslpath
  become: yes
  sysrc:
    name: dhparamgen_opensslpath
    value: "{{ dhparamgen_opensslpath }}"

- name: Set dhparamgen_pempath
  become: yes
  sysrc:
    name: dhparamgen_pempath
    value: "{{ dhparamgen_path }}"

- name: Set dhparamgen_logfile
  become: yes
  sysrc:
    name: dhparamgen_logfile
    value: "{{ dhparamgen_logfile }}"

- name: Create dhparam directory
  become: yes
  file:
    path="{{ dhparamgen_path }}"
    state=directory

- name: Start dhparamgen (if not running)
  become: yes
  service:
    name=dhparamgen
    state=started
